config/routes.rb
Rails.application.routes.draw do
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :leaders, only: [:index, :show]

  root to: 'trips#index'

  resources :trips, only: [:index, :show] do
    resources :attendees, except: [:index, :show]
  end

end

app/models/trip.rb
# == Schema Information
#
# Table name: trips
#
#  id           :integer          not null, primary key
#  title        :string(255)
#  leader       :integer
#  start_date   :date
#  end_date     :date
#  price        :integer
#  created_at   :datetime
#  updated_at   :datetime
#  description  :text
#  custom       :boolean          default(FALSE)
#  private_trip :boolean          default(FALSE)
#

class Trip < ActiveRecord::Base
	has_many :attendees

	validates :title, presence: true
	validates :leader, presence: true
	validates :price, presence: true
	
  #default_scope -> { where( 'start_date > ?', Date.today - 1).all}
  default_scope -> { order(:start_date => :asc)}

  after_create :notify_of_private

	def get_leader
		Leader.find(self.leader)
	end

  def notify_of_private
    if self.private_trip?
      TripMailer.notify_admin(self).deliver
    end
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @trips = Trip.where(:private_trip => false).paginate(:page => params[:page], :per_page => 20)
  end

  def show
    @leader = Leader.find(@trip.leader)
    @trip_attendees = @trip.attendees.all
  end

  def new
    @trip = Trip.new
  end

  def edit
  end

  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        flash[:success] = 'Trip was successfully created.'
        format.html { redirect_to @trip}
        format.json { render :show, status: :created, location: @trip }
      else
        flash[:danger] = 'Trip could not be created.'
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @trip.update(trip_params)
        flash[:success] = 'Trip was successfully updated.'
        format.html { redirect_to @trip }
        format.json { render :show, status: :ok, location: @trip }
      else
        flash[:danger] = 'Trip could not be updated.'
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @trip.destroy
    respond_to do |format|
      flash[:success] = 'Trip was successfully destroyed.' 
      format.html { redirect_to trips_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:title, :leader, :start_date, :end_date, :price)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for(@trip), :html=> {:id => 'attendee-signup-form'} do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.number_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date, class: "form-control" %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">
  var form = document.getElementById('attendee-signup-form');
  analytics.trackForm(form, 'Attendee Signup');
</script>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<% provide(:title, "Trips") %>

<h1>Listing Trips</h1>


<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Start Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= link_to trip.title, trip %></td>

        <% if trip.custom? %>
          <td>Pay What You Want</td>
        <% else %>
          <td><%= number_to_currency(trip.price, :unit => "$") %></td>
        <% end %>
        
        <% if trip.start_date? %>
          <td><%= trip.start_date.strftime("%m/%d/%Y") %></td>
        <% else %>
          <td>TBD</td>
        <% end %>

        <td><%= link_to 'Sign up', new_trip_attendee_path(trip), class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @trips, renderer: BootstrapPagination::Rails  %>


<br>

app/views/trips/new.html.erb
<% provide(:title, 'New Trip') %>

<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<% provide(:title, @trip.title) %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3><%= @trip.title %></h3>
    <h4><%= link_to @leader.name, @leader %></h4>
    <% if @trip.start_date? && @trip.end_date? %>
      <p> From <%= @trip.start_date.strftime("%B %d, %Y") %> to <%= @trip.end_date.strftime("%B %d, %Y") %>.</p>
    <% else %>
      <p>Dates TBD</p>
    <% end %>
    <h4><strong>Price: </strong>$<%= @trip.price %></h4>
  </div>

  <div class="panel-body">
    <% if @trip.description %>
      <p><%= @trip.description %></p>
    <% else %>
      <p>Looks like we don't have a description for this trip.  That's okay!  It's still real!  You should be able to find any details at <a href="http://vestigo.co">vestigo.co</a> and if you have any questions feel free to email us at <a href="mailto:issues@vestigo.co">issues@vestigo.co</a></p>
    <% end %>
  </div>
</div>


<%= link_to 'Sign Up Now', new_trip_attendee_path(@trip), class: 'btn btn-success', id: "signup-link" %>  <br>

<% if @trip_attendees.any? %>
  <h3>Attendees</h3>
  <ul>
    <% @trip_attendees.each do |attendee| %>
      <li><%= attendee.name %></li>
    <% end %>
  </ul>
<% end %>

<script type="text/javascript">
  $("#signup-link").click(function() {
    analytics.track("Click Sign Up");
  });
</script>