config/routes.rb
Rails.application.routes.draw do
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :leaders, only: [:index, :show]

  root to: 'trips#index'

  resources :trips, only: [:index, :show] do
    resources :attendees, except: [:index, :show]
  end

end

app/models/attendee.rb
# == Schema Information
#
# Table name: attendees
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  email       :string(255)
#  phone       :string(255)
#  trip_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#  paid        :boolean          default(FALSE)
#  card_error  :boolean          default(FALSE)
#  customer_id :string(255)
#

class Attendee < ActiveRecord::Base
	belongs_to :trip

  #these are the model validations
  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true

  after_create :send_notification
  after_create :admin_messages

	def get_customer_from_stripe
    # Add customer id to User model
    cus_id = self.customer_id
    customer = Stripe::Customer.retrieve(cus_id)
    return customer
  end

  def create_stripe_customer(params, token)
    customer = Stripe::Customer.create(
      description: "Vestigo Customer",
      email: params[:attendee][:email],
      card: token.id
    )
    self.update_attributes(customer_id: customer.id)
  end

  def charge_stripe(amount, params)
    token = self.create_stripe_token(params)

    unless self.customer_id
      self.create_stripe_customer(params, token)
    end

    charge = Stripe::Charge.create(
      customer: self.customer_id,
      amount: amount,
      description: "Vestigo Trip charge",
      currency: 'usd'
    )
    return charge
  end

  def create_stripe_token(params)
    token = Stripe::Token.create(
      card: {
        number: params[:number],
        exp_month: exp_month_year_to_month(params[:credit_card_expiry]),
        exp_year: exp_month_year_to_year(params[:credit_card_expiry]),
        cvc: params[:cvc]
      }
    )
    return token
  end

  def send_notification
    AttendeeMailer.new_attendee(self)
  end


  def admin_messages
    first = is_first?

    if first == true
      first_message
    else
      new_sign_up_message
    end
  end

  def is_first?

    count = self.trip.attendees.count

    if count > 1
      false
    else
      true
    end

  end

  def first_message
    AttendeeMailer.first_message(self).deliver
  end

  def new_sign_up_message
    AttendeeMailer.new_sign_up_message(self).deliver
  end

  private

    def exp_month_year_to_month(monthyear)
      month = monthyear.split(" / ").first
      return month
    end

    def exp_month_year_to_year(monthyear)
      year = monthyear.split(" / ").last
      return year
    end

end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_attendee, only: [:show, :edit, :update, :destroy]
  before_action :set_trip, only: [:index, :new, :create, :edit, :update, :destroy]

  def index
    @attendees = @trip.attendees.all
  end

  def show
  end

  def new
    @attendee = @trip.attendees.new
  end

  def edit
  end

  def create
    @attendee = @trip.attendees.new(attendee_params)

    if @trip.custom?
      params[:amount] = params[:amount].to_i * 100
    end

    if @attendee.valid?
      begin
        @attendee.charge_stripe(params[:amount], params)
      rescue Stripe::CardError => e
        flash.now[:danger] = e.message
        render :new and return
      rescue Stripe::InvalidRequestError => e
        flash.now[:danger] = e.message
        render :new and return
      end
    else
      flash.now[:danger] = "Something went wrong with your registration.  Don't worry, we didn't charge your card."
      render :new and return
    end

    respond_to do |format|
      if @attendee.save
        @attendee.update(paid: true)
        flash[:success] = "You successfully signed up!"
        format.html { redirect_to root_url }
      else
        flash.now[:danger] = "Something went wrong with your registration."
        format.html { render :new }
      end
    end
  end

  def update

    respond_to do |format|
      if @attendee.update(attendee_params)
        flash[:success] = "Attendee was successfully updated."
        format.html { redirect_to root_url}
      else
        flash[:danger] = "Attendee could not be updated."
        format.html { render :new }
      end
    end
  end

  def destroy
    @attendee.destroy
    respond_to do |format|
      flash[:success] = "Attendee was destroyed.  Utterly."
      format.html { redirect_to trips_url}
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:trip_id])
    end

    def set_attendee
      @attendee = Attendee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendee_params
      params.require(:attendee).permit(:name, :email, :phone, :trip_id)
    end

end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/attendees/_form.html.erb
<%= form_for(@attendee, url: trip_attendees_path, html: {id: "payment-form"}) do |f| %>
  <% if @attendee.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@attendee.errors.count, "error") %>
      </div>
      <ul>
      <% @attendee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag :email %>
  <%= hidden_field_tag :token %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control email" %>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <p style="display: inline-block; float: right; font-size: 0.7em;">*We're only asking for your number in case we need to text you trip updates.</p>
    <%= f.text_field :phone, class: "form-control phone_number" %>
  </div>

  <div class="form-group">
    <% if @trip.custom? %>
      <h4>Pay What You Want Amount</h4>
      <small>This generous trip leader is using a "Pay What You Want" format, so enter what you think this is worth.</small>
    <% end %>
  </div>

  <div class="form-group">
    <div class="col-md-8" style="padding: 0.2em;">
      <label>Card Number</label>
      <%= text_field_tag :number, nil, :class => "credit_card_number form-control"%>
    </div>
    <div class="col-md-4" style="padding: 0.2em;">
      <label>Price</label>
      <% if @trip.custom? %>
        <%= text_field_tag :amount, nil, :class => "number form-control"%>
      <% else %>
        <%= text_field_tag :fake_amount, "$#{@trip.price}.00" , disabled: true, :class => "number form-control" %>
        <%= hidden_field_tag :amount, @trip.price*100 %>
      <% end %>
    </div>
  </div>

  <div class="form-row">
    <div class="col-md-4" style="padding: 0.2em;">
      <label>Expiration Date</label>
      <%= text_field_tag :credit_card_expiry, nil, :class => "credit_card_expiry form-control", :placeholder => "MM / YYYY" %>
    </div>
    <div class="col-md-4" style="padding: 0.2em;">
      <label>CVC</label>
      <%= text_field_tag :cvc, nil, :class => "credit_card_cvc form-control" %>
    </div>
  </div>

  <%= f.submit "Sign me up!", :class => "btn btn-success btn-lg", :id => "register", :style => "width: 100%;" %>

<% end %>

<script>
  jQuery(function($){
    fields = ['credit_card_number',
              'credit_card_expiry',
              'credit_card_cvc',
              'email',
              'phone_number']

    $('#register').attr('disabled', 'disabled');

    $.each( fields, function (index, value) {
      $('input.'+value).formance('format_'+value)
                         .addClass('form-control')
                         .wrap('<div class=\'form-group\' />');

      $('input.'+value).on('keyup change blur', function (value) {
        return function (event) {
          $this = $(this);
          if ($this.formance('validate_'+value)) {
              $this.parent()
                      .removeClass('has-success has-error')
                      .addClass('has-success');
          } else {
              $this.parent()
                      .removeClass('has-success has-error')
                      .addClass('has-error');

          }
        }
      }(value));
    });
  });
</script>

<script>

  (function() {
    $('#number, #credit_card_expiry, #cvc, #attendee_email, #attendee_phone, #attendee_name, #amount').keyup(function() {

        var empty = false;
        $('#number, #credit_card_expiry, #cvc, #attendee_email, #attendee_phone, #attendee_name, #amount').each(function() {
            if ($(this).val() == '') {
                empty = true;
            }
        });

        if (empty) {
            $('#register').attr('disabled', 'disabled'); 
        } else {
            $('#register').removeAttr('disabled'); 
        }
    });
  })()
</script>

app/views/attendees/edit.html.erb
<h1>Edit this Attendee info</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/attendees/index.html.erb
<h1>Attendee#index</h1>
<p>Find me in app/views/attendee/index.html.erb</p>

app/views/attendees/new.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <h1>Sign up for <%= @trip.title %>!</h1>
    <h5 class="pull-right">Hey there. All fields are required</h5>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
  <%= render 'form' %>
</div>
</div>

<%= link_to 'Back', trips_path %>

app/views/attendees/show.html.erb
<h1>Attendee#show</h1>
<p>Find me in app/views/attendee/show.html.erb</p>