config/routes.rb
Rails.application.routes.draw do
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :leaders, only: [:index, :show]

  root to: 'trips#index'

  resources :trips, only: [:index, :show] do
    resources :attendees, except: [:index, :show]
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Vestigo Schedule Beta, by <a href="http://vestigo.co" target="_blank">Vestigo Adventures, LLC</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Terms", '#'%></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div id="logo">
        <a href="http://vestigo.herokuapp.com"><img src="<%= image_path('logo.png') %>" class="img-responsive" ></a>
      </div>
    </div>

  	<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Trips", trips_path %></li>
        <li><%= link_to "Leaders", leaders_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	</head>

	<body>
	
		<%= render 'layouts/header' %>

		<div class="container">
		
			<% flash.each do |name, msg| %>
	    	<%= content_tag :div, msg, class: "alert alert-#{name}" %>
	    <% end %>

			<%= yield %>

			<%= render 'layouts/footer' %>
			
		</div>

	</body>
</html>